service: championship-management-mtg

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 29
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    ABLY_API_KEY: ${env:ABLY_API_KEY}

plugins:
  # - serverless-offline

custom:
  # serverless-offline:
  #   httpPort: 4000

package:
  patterns:
    - "src/**"
    - "build/**"

functions:
  api:
    handler: src/handler.handler
    memorySize: 512
    timeout: 29
    events:
      - http:
          path: /
          method: any
          cors:
            origins:
              - "*"
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          path: /{proxy+}
          method: any
          cors:
            origins:
              - "*"
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

outputs:
  usuarioCadastrar:
    Description: "Rota de cadastro de usuários"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/usuario/cadastrar"

  usuarioLogin:
    Description: "Rota de login de usuários"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/usuario/login"

  usuarioAtualizar:
    Description: "Rota de atualizar dados do usuário"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/usuario/atualizar"

  deckCadastrar:
    Description: "Rota de cadastro de decks"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/deck/cadastrar"

  deckListar:
    Description: "Rota de listagem de decks do usuário"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/deck/listar"

  deckAtualizar:
    Description: "Rota de atualizar deck"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/deck/atualizar/{id}"

  deckExcluir:
    Description: "Rota de exclusão de decks"
    Value: !Sub "https://${self:service}.execute-api.${aws:region}.amazonaws.com/${sls:stage}/deck/excluir/{id}"
